name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  OPENUCX_LINK: https://github.com/openucx/ucx.git
  UCC_LINK: https://github.com/zasdfgbnm/ucc.git

jobs:
  system:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        PROJECT: [ucx, ucc]

    steps:
    - uses: actions/checkout@v2

    - name: Get UCX
      run: |
        set -eux
        git clone ${OPENUCX_LINK} /tmp/ucx
        cd /tmp/ucx &&
        ./autogen.sh
        ./contrib/configure-release-mt --without-java --disable-numa --prefix=/opt/ucx
        make -j install

    - name: Get UCC
      if: contains(matrix.PROJECT, 'ucc')
      run: |
        set -eux
        git clone ${UCC_LINK} -b cmake /tmp/ucc
        cd /tmp/ucc
        ./autogen.sh
        ./configure --with-ucx=/opt/ucx --prefix=/opt/ucc
        make -j install
        mkdir -p /opt/ucc/lib/cmake/ucc/
        cp -r cmake/*.cmake /opt/ucc/lib/cmake/ucc/

    - name: Configure CMake
      run: |
        set -eux
        mkdir -p build/${{matrix.PROJECT}}
        cmake -DCMAKE_MODULE_PATH=$PWD/cmake -S Tests/Find${{matrix.PROJECT}}/Test -B build/${{matrix.PROJECT}}

    - name: Build
      working-directory: ${{github.workspace}}/build/${{matrix.PROJECT}}
      run: cmake --build . --verbose

    - name: Test
      working-directory: ${{github.workspace}}/build/${{matrix.PROJECT}}
      run: ctest -R '.*'

