name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        BUILD_TYPE: [Release, Debug, RelWithDebInfo]

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: |
        set -eux
        cmake -S ${{github.workspace}}/test/ucx -B ${{github.workspace}}/build/ucx -DCMAKE_BUILD_TYPE=${{matrix.BUILD_TYPE}}
        cmake -S ${{github.workspace}}/test/ucc -B ${{github.workspace}}/build/ucc -DCMAKE_BUILD_TYPE=${{matrix.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{matrix.BUILD_TYPE}}
      
