name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  OPENUCX_LINK: https://github.com/openucx/ucx.git
  UCC_LINK: https://github.com/openucx/ucc.git

jobs:
  system:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get UCX
      run: |
        set -eux
        git clone ${OPENUCX_LINK} /tmp/ucx
        cd /tmp/ucx &&
        ./autogen.sh
        ./contrib/configure-release-mt --without-java --disable-numa --prefix=/opt/ucx
        make -j install

    - name: Get UCC
      run: |
        set -eux
        git clone ${UCC_LINK} /tmp/ucc
        cd /tmp/ucc
        ./autogen.sh
        ./configure --with-ucx=/opt/ucx --prefix=/opt/ucc
        make -j install

    - name: Configure CMake
      run: |
        set -eux
        mkdir -p build
        cmake -S . -B build

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --verbose

    - name: Test
      timeout-minutes: 1
      run: ctest .

